"""
    build_induction_machine_alpha_beta_eqs(vars, pars)

Builds the induction machine plant equations in stationary αβ coordinates.

Plant inputs:
- `vsα`
- `vsβ`
- `Tload_cmd`

Plant states:
- `isα`, `isβ`
- `irα`, `irβ`
- `ωm`, `θm`

Plant outputs:
- `Te`
- `n_rpm`
- fluxes and currents

The plant does not know whether the voltage was generated by scalar control,
FOC, a measured profile, or another controller.
"""
function build_induction_machine_alpha_beta_eqs(vars, pars)

    # Electrical inputs from controller / ideal voltage source
    vsα = vars.vsα
    vsβ = vars.vsβ

    # Mechanical input
    Tload_cmd = vars.Tload_cmd

    # Electrical plant states
    isα = vars.isα
    isβ = vars.isβ
    irα = vars.irα
    irβ = vars.irβ

    # Fluxes
    ψsα = vars.ψsα
    ψsβ = vars.ψsβ
    ψrα = vars.ψrα
    ψrβ = vars.ψrβ

    # Mechanical states
    ωm = vars.ωm
    θm = vars.θm

    # Outputs
    Te = vars.Te
    n_rpm = vars.n_rpm
    n_sync_rpm = vars.n_sync_rpm

    # Frequency command only used here to provide useful synchronous-speed output.
    # It is not a plant input in the physical sense.
    f_cmd = vars.f_cmd

    # Parameters
    Rs = pars.Rs
    Rr = pars.Rr
    Lls = pars.Lls
    Llr = pars.Llr
    Lm = pars.Lm
    p = pars.p
    J = pars.J
    B = pars.B

    Ls = Lls + Lm
    Lr = Llr + Lm

    return [
        # Flux-current relations
        ψsα ~ Ls * isα + Lm * irα,
        ψsβ ~ Ls * isβ + Lm * irβ,

        ψrα ~ Lm * isα + Lr * irα,
        ψrβ ~ Lm * isβ + Lr * irβ,

        # Stator voltage equations
        vsα ~ Rs * isα + D(ψsα),
        vsβ ~ Rs * isβ + D(ψsβ),

        # Squirrel-cage rotor equations in stationary alpha-beta frame
        0 ~ Rr * irα + D(ψrα) + p * ωm * ψrβ,
        0 ~ Rr * irβ + D(ψrβ) - p * ωm * ψrα,

        # Electromagnetic torque
        Te ~ 1.5 * p * (ψsα * isβ - ψsβ * isα),

        # Mechanical dynamics
        J * D(ωm) ~ Te - Tload_cmd - B * ωm,
        D(θm) ~ ωm,

        # Useful outputs
        n_rpm ~ ωm * 60 / (2π),
        n_sync_rpm ~ 60 * f_cmd / p,
    ]
end